#!/usr/bin/env python3
"""
~/.config/hypr/scripts/toggle-workspace-layout.py
Toggles the active workspace layout between 'dwindle' and 'scrolling',
applies the change live in Hyprland, and persists the setting across reboots.
"""

import json
import os
import re
import subprocess
import sys


def run_cmd(args):
    try:
        return subprocess.check_output(args, stderr=subprocess.DEVNULL).decode("utf-8")
    except Exception:
        return ""


def main():
    # 1. Query active workspace info
    out = run_cmd(["hyprctl", "activeworkspace", "-j"])
    if not out:
        sys.exit(1)

    try:
        data = json.loads(out)
    except Exception:
        sys.exit(1)

    ws_name = str(data.get("name", "1"))
    current_layout = data.get("tiledLayout", "dwindle").lower()

    # 2. Toggle layout
    if current_layout == "scrolling":
        new_layout = "dwindle"
    else:
        new_layout = "scrolling"

    # 3. Apply live in Hyprland via Lua eval
    eval_code = f'hl.workspace_rule({{ workspace = "{ws_name}", layout = "{new_layout}" }})'
    subprocess.call(["hyprctl", "eval", eval_code], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    # 4. Manage persistent configuration file
    config_dir = os.path.expanduser("~/.config/hypr")
    persist_file = os.path.join(config_dir, "workspace-layouts.lua")

    rules = {}
    rule_regex = re.compile(r'hl\.workspace_rule\(\{\s*workspace\s*=\s*["\']([^"\']+)["\']\s*,\s*layout\s*=\s*["\']([^"\']+)["\']\s*\}\)')

    if os.path.exists(persist_file):
        try:
            with open(persist_file, "r", encoding="utf-8") as f:
                for line in f:
                    match = rule_regex.search(line)
                    if match:
                        rules[match.group(1)] = match.group(2)
        except Exception:
            pass

    # Update active workspace rule
    rules[ws_name] = new_layout

    # Write sorted rules
    def sort_key(k):
        try:
            return (0, int(k))
        except ValueError:
            return (1, k)

    lines = [
        "-- ~/.config/hypr/workspace-layouts.lua",
        "-- Automatically generated by toggle-workspace-layout.py",
        "-- Persists per-workspace layout selections across reboots",
        "",
    ]
    for k in sorted(rules.keys(), key=sort_key):
        lines.append(f'hl.workspace_rule({{ workspace = "{k}", layout = "{rules[k]}" }})')
    lines.append("")

    content = "\n".join(lines)

    # Write locally to ~/.config/hypr/workspace-layouts.lua
    try:
        with open(persist_file, "w", encoding="utf-8") as f:
            f.write(content)
    except Exception as e:
        sys.stderr.write(f"Error writing persist file: {e}\n")

    # Sync to ~/Tegmentum-OS if repository directory exists
    tegmentum_dir = os.path.expanduser("~/Tegmentum-OS/.config/hypr")
    if os.path.exists(tegmentum_dir):
        try:
            tegmentum_persist = os.path.join(tegmentum_dir, "workspace-layouts.lua")
            with open(tegmentum_persist, "w", encoding="utf-8") as f:
                f.write(content)
        except Exception:
            pass

    # 5. Visual Notification
    icon_symbol = "󰕰" if new_layout == "scrolling" else "󱂬"
    notify_title = "Workspace Layout Changed"
    notify_body = f"Workspace {ws_name}: {new_layout.upper()} {icon_symbol}"

    # Desktop notification via notify-send
    subprocess.call([
        "notify-send",
        "-h", "string:x-canonical-private-synchronous:ws-layout",
        "-i", "preferences-desktop-display",
        notify_title,
        notify_body
    ], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    # Hyprland built-in notification
    color = "rgb(137,208,237)" if new_layout == "scrolling" else "rgb(179,202,213)"
    subprocess.call([
        "hyprctl", "notify", "1", "2000", color, f"Workspace {ws_name} ➔ {new_layout.upper()}"
    ], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


if __name__ == "__main__":
    main()
