# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock

$font = Roboto Mono
source = ~/.config/hypr/hyprlock-colors.conf

general {
    hide_cursor = false
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 5
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = $lock_outline
    check_color = $lock_check
    fail_color = $lock_fail

    font_color = $lock_font
    fade_on_empty = false
    rounding = 25

    font_family = $font
    placeholder_text = 
    fail_text = $PAMFAIL$FPRINTFAIL

    # check_text = Authenticating...
    # dots_text_format = *
    dots_size = 0.2
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, 0
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 60
    font_family = $font
    color = $lock_time
    position = 0, -130
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 16
    font_family = $font
    color = $lock_date

    position = 0, -250
    halign = center
    valign = top
}

# KEYBOARD LAYOUT
label {
    monitor =
    text = $LAYOUT[en,ru]
    font_size = 14
    font_family = $font
    onclick = hyprctl switchxkblayout all next
    color = $lock_layout
    position = 0, -70
    halign = center
    valign = center
}

label {
    text = cmd[update:1] ~/.config/hypr/scripts/now-playing.sh

    position = 0, -300
    halign = center
    valign = center

    font_size = 15
    color = $lock_date
}
label {
    text = cmd[update:1] ~/.config/hypr/scripts/now-playing.sh previous

    position = -40, -370
    halign = center
    valign = center
    font_size = 28
    onclick = playerctl --player="$(~/.config/waybar/scripts/playerctl-active.sh)" previous
    color = $lock_date
}

label {
    text = cmd[update:1] ~/.config/hypr/scripts/now-playing.sh pause

    position = 0, -370
    halign = center
    valign = center
    font_size = 28
    onclick = playerctl --player="$(~/.config/waybar/scripts/playerctl-active.sh)" play-pause
    color = $lock_date
}

label {
    text = cmd[update:1] ~/.config/hypr/scripts/now-playing.sh next

    position = 40, -370
    halign = center
    valign = center
    font_size = 28
    onclick = playerctl --player="$(~/.config/waybar/scripts/playerctl-active.sh)" next
    color = $lock_date
}

label {
    text = cmd[update:1] ~/.config/hypr/scripts/password-cursor.sh

    position = 0, 2
    halign = center
    valign = center

    font_size = 18
    font_family = $font
    color = $lock_date
} 
