-- ~/.config/hypr/workspace-layouts.lua
-- Automatically generated by toggle-workspace-layout.py
-- Persists per-workspace layout selections across reboots

hl.workspace_rule({ workspace = "2", layout = "dwindle" })
hl.workspace_rule({ workspace = "7", layout = "scrolling" })
hl.workspace_rule({ workspace = "8", layout = "dwindle" })
