[Setting]
prefs_path             = /home/rp34/.config/spotify/prefs
current_theme          = text
color_scheme           = Monochrome
inject_css             = 1
replace_colors         = 1
check_spicetify_update = 1
spotify_path           = /opt/spotify/
inject_theme_js        = 1
overwrite_assets       = 0
spotify_launch_flags   = 
always_enable_devtools = 0

[Preprocesses]
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1

[AdditionalOptions]
extensions            = 
custom_apps           = marketplace
sidebar_config        = 0
home_config           = 1
experimental_features = 1

[AdditionalOptions]
spotify_flags = --enable-features=UseOzonePlatform|--ozone-platform=wayland   

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.2.92.147.g5b8f9367
with    = 2.45.0
